import { SupportedLanguage } from '../types';

export interface TTSOptions {
  lang: SupportedLanguage;
  phraseKey?: string;
  speechRate?: number; // 0.7 to 1.2
  onStart?: () => void;
  onEnd?: () => void;
  onError?: (err: any) => void;
}

const SARVAM_API_KEY =
  (typeof import.meta !== 'undefined' && (import.meta as any).env?.VITE_SARVAM_API_KEY) ||
  'sk_essjckqv_dhNR0boGxQvK69QQFxA1j5h0';
const SARVAM_ENDPOINT = 'https://api.sarvam.ai/text-to-speech';

export class VoiceOutputManager {
  private speechRate = 1.0;
  private audioCache = new Map<string, string>(); // phraseKey or textKey -> base64/dataURL
  private currentAudio: HTMLAudioElement | null = null;
  private lastSpokenText = '';
  private lastOptions: TTSOptions = { lang: 'en' };
  private availableVoices: SpeechSynthesisVoice[] = [];
  private isManifestLoaded = false;

  constructor() {
    this.preloadBundledAudioManifest();
    this.initVoices();
  }

  private initVoices() {
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      this.availableVoices = window.speechSynthesis.getVoices();
      window.speechSynthesis.onvoiceschanged = () => {
        this.availableVoices = window.speechSynthesis.getVoices();
      };
    }
  }

  private async preloadBundledAudioManifest() {
    // 1. Load from localStorage cache if available
    try {
      if (typeof window !== 'undefined' && window.localStorage) {
        const stored = localStorage.getItem('complan_audio_cache');
        if (stored) {
          const parsed = JSON.parse(stored);
          Object.entries(parsed).forEach(([k, v]) => this.audioCache.set(k, v as string));
        }
      }
    } catch (_) {}

    // 2. Fetch pre-cached audio manifest generated by Sarvam AI
    if (typeof window !== 'undefined') {
      try {
        const res = await fetch('/cached_audio_phrases.json');
        if (res.ok) {
          const manifest = await res.json();
          Object.entries(manifest).forEach(([k, v]) => {
            this.audioCache.set(k, v as string);
          });
          this.isManifestLoaded = true;
        }
      } catch (_) {}
    }
  }

  public setSpeechRate(rate: number) {
    this.speechRate = Math.max(0.6, Math.min(1.4, rate));
  }

  public makeSlower() {
    this.speechRate = 0.72;
    if (this.lastSpokenText) {
      this.speak(this.lastSpokenText, { ...this.lastOptions, speechRate: 0.72 });
    }
  }

  public repeat() {
    if (this.lastSpokenText) {
      this.speak(this.lastSpokenText, this.lastOptions);
    }
  }

  /**
   * Speak a phrase using:
   * Tier 1: Real Native Pre-cached audio (from Sarvam AI)
   * Tier 2: Real-time Sarvam AI online synthesis (when online & uncached)
   * Tier 3: Web Speech API STRICTLY matching target language (NO cross-language fallbacks)
   */
  public async speak(text: string, options: TTSOptions): Promise<void> {
    this.lastSpokenText = text;
    this.lastOptions = options;
    const rate = options.speechRate || this.speechRate;

    this.stop();

    // 1. Tier 1: Check Pre-cached audio manifest
    const textKey = `${options.lang}_${text.trim().toLowerCase().replace(/[^a-z0-9]/g, '_').slice(0, 45)}`;
    let audioSrc: string | undefined;

    if (options.phraseKey && this.audioCache.has(options.phraseKey)) {
      audioSrc = this.audioCache.get(options.phraseKey);
    } else if (this.audioCache.has(textKey)) {
      audioSrc = this.audioCache.get(textKey);
    } else if (this.audioCache.has(text)) {
      audioSrc = this.audioCache.get(text);
    }

    if (audioSrc) {
      await this.playAudioSource(audioSrc, rate, options);
      return;
    }

    // If manifest hasn't finished loading yet, try one direct lookup
    if (!this.isManifestLoaded && typeof window !== 'undefined') {
      try {
        const res = await fetch('/cached_audio_phrases.json');
        if (res.ok) {
          const manifest = await res.json();
          Object.entries(manifest).forEach(([k, v]) => this.audioCache.set(k, v as string));
          this.isManifestLoaded = true;

          const retrySrc = (options.phraseKey && manifest[options.phraseKey]) || manifest[textKey];
          if (retrySrc) {
            await this.playAudioSource(retrySrc, rate, options);
            return;
          }
        }
      } catch (_) {}
    }

    // 2. Tier 2: Dynamic online Sarvam AI TTS (Guarantees authentic native speaker)
    if (typeof window !== 'undefined' && navigator.onLine) {
      const generatedAudio = await this.fetchOnlineSarvamTTS(text, options.lang);
      if (generatedAudio) {
        this.audioCache.set(textKey, generatedAudio);
        if (options.phraseKey) {
          this.audioCache.set(options.phraseKey, generatedAudio);
        }
        await this.playAudioSource(generatedAudio, rate, options);
        return;
      }
    }

    // 3. Tier 3: Strict Browser Speech Synthesis
    // MANDATORY: Voice MUST be in the requested language, never any other language!
    this.speakNativeStrict(text, options.lang, rate, options);
  }

  private playAudioSource(src: string, rate: number, options: TTSOptions): Promise<void> {
    return new Promise((resolve) => {
      try {
        this.currentAudio = new Audio(src);
        this.currentAudio.playbackRate = rate;
        this.currentAudio.onplay = () => {
          options.onStart?.();
        };
        this.currentAudio.onended = () => {
          options.onEnd?.();
          this.currentAudio = null;
          resolve();
        };
        this.currentAudio.onerror = (e) => {
          this.currentAudio = null;
          this.speakNativeStrict(this.lastSpokenText, options.lang, rate, options);
          resolve();
        };
        this.currentAudio.play().catch((err) => {
          this.currentAudio = null;
          this.speakNativeStrict(this.lastSpokenText, options.lang, rate, options);
          resolve();
        });
      } catch (err) {
        this.currentAudio = null;
        this.speakNativeStrict(this.lastSpokenText, options.lang, rate, options);
        resolve();
      }
    });
  }

  private async fetchOnlineSarvamTTS(text: string, lang: SupportedLanguage): Promise<string | null> {
    const langTags: Record<SupportedLanguage, string> = {
      ml: 'ml-IN',
      ta: 'ta-IN',
      hi: 'hi-IN',
      en: 'en-IN'
    };

    try {
      const res = await fetch(SARVAM_ENDPOINT, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'api-subscription-key': SARVAM_API_KEY
        },
        body: JSON.stringify({
          inputs: [text],
          target_language_code: langTags[lang] || 'en-IN',
          speaker: 'kavya',
          model: 'bulbul:v3'
        })
      });

      if (!res.ok) return null;
      const data = await res.json();
      if (data.audios && data.audios[0]) {
        return `data:audio/wav;base64,${data.audios[0]}`;
      }
      return null;
    } catch {
      return null;
    }
  }

  /**
   * Browser SpeechSynthesis with STRICT language verification
   * Under no condition will a Malayalam/Tamil page speak with a Hindi/English voice!
   */
  private speakNativeStrict(text: string, lang: SupportedLanguage, rate: number, options: TTSOptions) {
    if (typeof window === 'undefined' || !('speechSynthesis' in window)) {
      options.onError?.('SpeechSynthesis is not supported in this browser.');
      return;
    }

    window.speechSynthesis.cancel();

    if (this.availableVoices.length === 0) {
      this.availableVoices = window.speechSynthesis.getVoices();
    }

    const langMatchers: Record<SupportedLanguage, (v: SpeechSynthesisVoice) => boolean> = {
      ml: (v) => {
        const code = v.lang.toLowerCase();
        const name = v.name.toLowerCase();
        return code.startsWith('ml') || name.includes('malayalam');
      },
      ta: (v) => {
        const code = v.lang.toLowerCase();
        const name = v.name.toLowerCase();
        return code.startsWith('ta') || name.includes('tamil');
      },
      hi: (v) => {
        const code = v.lang.toLowerCase();
        const name = v.name.toLowerCase();
        return code.startsWith('hi') || name.includes('hindi');
      },
      en: (v) => {
        const code = v.lang.toLowerCase();
        const name = v.name.toLowerCase();
        return code.startsWith('en') || name.includes('english');
      }
    };

    const matcher = langMatchers[lang] || langMatchers.en;
    const voice = this.availableVoices.find(matcher);

    if (!voice) {
      // STRICT REQUIREMENT: If the OS lacks the exact language voice pack,
      // DO NOT speak using a different language!
      options.onError?.(`No native ${lang.toUpperCase()} voice installed on this device.`);
      return;
    }

    const utterance = new SpeechSynthesisUtterance(text);
    utterance.lang = voice.lang;
    utterance.voice = voice;
    utterance.rate = rate;
    utterance.pitch = 1.0;

    utterance.onstart = () => options.onStart?.();
    utterance.onend = () => options.onEnd?.();
    utterance.onerror = (e) => {
      options.onError?.(e);
    };

    window.speechSynthesis.speak(utterance);
  }

  public stop() {
    if (this.currentAudio) {
      this.currentAudio.pause();
      this.currentAudio.currentTime = 0;
      this.currentAudio = null;
    }
    if (typeof window !== 'undefined' && 'speechSynthesis' in window) {
      window.speechSynthesis.cancel();
    }
  }
}
